[master]Update Jarvis Profile
jarviscanada/jarvis_data_eng_VishaySingh pull request #3
Opened 2022-05-18 18:28 UTC by V35games

## [master]Update Jarvis Profile

### Changes
- Added all Jarvis Profile-related files to the new `profile` directory
- Updated profile information

### Testing
-   [X] Tested with the provided bash script

2022-07-21 18:48 UTC, jarviscanada requested changes
See comments

2022-07-21 18:48 UTC, jarviscanada commented on README.md
> +playing video games, or learning guitar.
Lots of flavour, but need more technical details on your skills and experience. What projects have you worked on, what technologies have you used, what sorts of problems have you spent time on or like to solve, etc. This introduction should essentially include a highlights/summary of the rest of the profile.

2022-07-21 18:48 UTC, jarviscanada commented on README.md
> +playing video games, or learning guitar.
Take a look at these sample profiles for ideas (I do like the attitude and personal flair you express here though, try not to lose that)
https://github.com/jarviscanada/jarvis_data_eng_BrandonDicicco
https://github.com/jarviscanada/jarvis_data_eng_JohnCao
https://github.com/jarviscanada/jarvis_data_eng_TomasRotbauer
https://github.com/jarviscanada/jarvis_data_eng_TinaLee
https://github.com/jarviscanada/jarvis_data_eng_NarimanAlimuradov
https://github.com/jarviscanada/jarvis_data_eng_JasmeetBrar
https://github.com/jarviscanada/jarvis_data_eng_AlexKirilenko
https://github.com/jarviscanada/jarvis_data_eng_FatimaAnwer

2022-07-21 18:48 UTC, jarviscanada commented on README.md
> +**Proficient:** Java, Linux/Bash, RDBMS/SQL, Agile/Scrum, Git, Python, IDEs (IntelliJ, Visual Studio Code, Eclipse, PyCharm, etc.), REST API, Docker, DAO design pattern, CRUD, JDBC, Regular Expressio
Some of the more generic, highly-specific, or non-technical elements don't need to be listed here. E.g. IDEs, CRUD, RegEx, Lambda/Stream, MVC. These are either generally expected or included within other things you've listed.

2022-07-21 18:48 UTC, jarviscanada commented on README.md
> +**Cloud/DevOps** [[GitHub](https://github.com/jarviscanada/jarvis_data_eng_VishaySingh/tree/master/cloud_devops)]: Not started.
remove/comment out projects that haven't been started.

2022-07-21 18:48 UTC, jarviscanada commented on README.md
> +stand-up meetings during the first and fifth sprints, which coordinated and tracked scrum team progress.
Don't specify which sprints you lead. This is one of those scenarios where less is more.

2022-07-21 18:48 UTC, jarviscanada commented on README.md
> +  - Twitter App: Designed, implemented, tested, and deployed a backend Java app that can CRUD tweets using Twitter's REST API. Common design patterns & frameworks were leveraged to design this app, s
Only CRD

2022-07-21 20:05 UTC, V35games commented
I just pushed changes that should address the comments. Please review when possible.

2022-07-22 16:17 UTC, jarviscanada approved these changes

2022-07-22 16:31 UTC, merged